### ISSUE TITLE
Subprocess Error

### ISSUE THREAD

**Issue by karregan** [kanaka/websockify#130]
I am trying to get the telnet stuff working. As the readme says, I run the line code:

```
./run 2023 --wrap-mode=respawn -- telnetd -debug 2023
```

and I get this as result:

```
WebSocket server settings:
  - Listen on :2023
  - Flash security policy server
  - No SSL/TLS support (no cert file)
  - proxying from :2023 to 'telnetd -debug 2023' (port 57906)
Starting 'telnetd -debug 2023'
Traceback (most recent call last):
  File "./run", line 5, in <module>
    websockify.websocketproxy.websockify_init()
  File "/home/stefo/tmp/websockify-master/websockify/websocketproxy.py", line 419, in websockify_init
    server.start_server()
  File "/home/stefo/tmp/websockify-master/websockify/websocket.py", line 910, in start_server
    self.started()  # Some things need to happen after daemonizing
  File "/home/stefo/tmp/websockify-master/websockify/websocketproxy.py", line 267, in started
    self.run_wrap_cmd()
  File "/home/stefo/tmp/websockify-master/websockify/websocketproxy.py", line 238, in run_wrap_cmd
    self.wrap_cmd, env=os.environ, preexec_fn=_subprocess_setup)
  File "/usr/lib/python2.7/subprocess.py", line 679, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1249, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
```

Can anyone help me? :D
Thank you

**Comment by leothelocust** [comment]
What was the solution here? I'm having the same issue.

**Comment by meihuabo** [comment]
What was the solution here? I'm having the same issue.

**Comment by kanaka** [comment]
This means it tried to launch `telnetd` but no executable was found by that name (or it's not on the path). You probably need to install the telnet daemon (e.g. inetutils-telnetd package on ubuntu).

**Comment by akrisiun** [comment]
for macOS Telnet is not available anymore on High Sierra
`brew install inetutils`
then :
```
which telnet -> /usr/local/bin/telnet
websockify $ sudo ./run 127.0.0.1:80 --wrap-mode=respawn -- /usr/local/bin/telnet www.google.co.uk 80
WebSocket server settings:
  - Listen on 127.0.0.1:80
  - SSL/TLS support
  - proxying from 127.0.0.1:80 to '/usr/local/bin/telnet www.google.co.uk 80' (port 57277)
Starting '/usr/local/bin/telnet www.google.co.uk 80'
Trying 64.233.161.94...
Connected to www.google.co.uk.
Escape character is '^]'.
GET /
HTTP/1.0 302 Found
Cache-Control: private
Content-Type: text/html; charset=UTF-8
Referrer-Policy: no-referrer
Location: http://www.google...
```
