### ISSUE TITLE
Tests (run by tox) are failing

### ISSUE THREAD

**Issue by haypo** [kanaka/websockify#171]
Hi,

I'm trying to run tests on Python 3.4 to check if websockify supports Python 3 or not. The problem is that tests are failing even on Python 2.7:

```
haypo@smithers$ tox -r -e py27
...
======================================================================
ERROR: testsocket_set_keepalive_options (test_websocket.WebSocketTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/haypo/prog/openstack/websockify/tests/test_websocket.py", line 65, in setUp
    ssl_only=False)
  File "/home/haypo/prog/openstack/websockify/tests/test_websocket.py", line 80, in _get_websockserver
    **kwargs)
TypeError: __init__() takes at least 2 arguments (8 given)

======================================================================
ERROR: test_new_client (test_websocketproxy.WebSocketProxyTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/haypo/prog/openstack/websockify/tests/test_websocketproxy.py", line 127, in test_new_client
    self.assertRaises(Exception, web_socket_proxy.new_websocket_client)
AttributeError: 'WebSocketProxy' object has no attribute 'new_websocket_client'
...
FAILED (errors=14)
```

Note: It looks like websockify supports Python 3, I saw many references to Python 3, but the Python 3 classifier miss in setup.py. You may add it if Python 3 is supported.

**Comment by DirectXMan12** [comment]
Thanks for the heads up!  The unit tests were quite out of date.  They are being updated (see #172 )
